# Generated by Django 5.1.1 on 2024-10-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messages_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
